# Generated by Django 3.1.2 on 2021-03-16 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=20)),
                ('visa', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('periodicidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='vuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateTimeField()),
                ('fecha_llegada', models.DateTimeField()),
                ('costo', models.IntegerField()),
                ('estado', models.BooleanField()),
                ('capacidad', models.IntegerField()),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='flights.ciudad')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origen', to='flights.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('nombre', models.CharField(max_length=20)),
                ('cc', models.CharField(max_length=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='interface_vacuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.ciudad')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.vacuna')),
            ],
        ),
        migrations.CreateModel(
            name='interface_impuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.ciudad')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.impuesto')),
            ],
        ),
        migrations.CreateModel(
            name='escala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.ciudad')),
                ('vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.vuelo')),
            ],
        ),
    ]
